[basic]
app_id=workflow_scheduler
app_name=定时任务调度
app_pk=1

[code]
pull_api_url=http://76.10.14.166:8888/apm/app-pull-src

[auth]
admin_username=admin
admin_password_cipher=d4a0d164b4f301417df3fb9b71a993c4
admin_token=dee8d840403811ebbd7400d8618f6760

[runtime]
avatar_url=/static/img/head.gif
repo_path=.
code_remote=origin
code_branch=workflow_scheduler
mpcm_access_token=eyJpYXQiOjE2MjkyNTE1MDMsImV4cCI6MTYyOTg1NjMwMywidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlcyI6InJvbGUiLCJwZXJtaXNzaW9uIjpbInVzZXIiXX0
enable_scheduler=true
scheduler_control_url=

[dev_run_job]
# 测试环境启动的自定义job
# 根据任务自行测试
# 举例aaa,bbb 启动 aaa 和 bbb pid
pid = mails_push_online_excel,mails_push_query_excel
# 控制是否全部运行 true/false
run_all = false

