import assert from 'node:assert/strict';
import { defaultCamera, moveCamera, layoutTasks, minuteOf, createMatrixScene, createPerspectiveProjection } from '../src/executionMatrixScene.js';
const camera=defaultCamera();
moveCamera(camera,0,50,0);
assert.equal(camera.yaw,-32,'Right drag must subtract yaw');
moveCamera(camera,0,0,1000);assert.equal(camera.pitch,274,'Pitch must continue past vertical');
moveCamera(camera,0,0,2880);assert.equal(camera.pitch,994,'Multiple full rotations must remain unrestricted');
moveCamera(camera,0,0,-6000);assert.equal(camera.pitch,-506,'Negative pitch must remain unrestricted');
moveCamera(camera,2,0,-20);assert.ok(camera.zoom>1,'Upward right drag enlarges');
moveCamera(camera,1,20,-30);assert.equal(camera.x,20);assert.equal(camera.y,-30);
const tasks=[24,8,68].flatMap((count,g)=>Array.from({length:count},(_,i)=>({pid:`${g}-${String(i).padStart(3,'0')}`,group:`分类${g}`})));
const layout=layoutTasks(tasks.reverse());
assert.equal(layout.positions.size,100);
assert.deepEqual(layout.groups.map(g=>g.cols),[3,1,8]);
assert.equal(new Set([...layout.positions.values()].map(p=>`${p.x},${p.z}`)).size,100);
assert.ok(layout.groups[1].x>layout.groups[0].x+layout.groups[0].cols);
assert.deepEqual([...layoutTasks(tasks).positions.keys()],[...layoutTasks(tasks.reverse()).positions.keys()]);
assert.equal(minuteOf('2026-10-01 13:30:30'),810.5);
const box={min:[-4,-4,-4],max:[4,4,4]};
const lens=createPerspectiveProjection(box,{...defaultCamera(),yaw:0,pitch:0},1400,700);
const apparentWidth=z=>lens.project(1,0,z)[0]-lens.project(-1,0,z)[0];
assert.ok(apparentWidth(3)>apparentWidth(-3)*1.2,'Equal rectangles closer to the camera must look larger');
for(const yaw of [-720,-180,0,90,360,1080])for(const pitch of [-450,-90,0,90,180,270,744]) {
  const lens=createPerspectiveProjection(box,{...defaultCamera(),yaw,pitch},390,460);
  for(const x of [-4,4])for(const y of [-4,4])for(const z of [-4,4]) {
    const p=lens.project(x,y,z);
    assert.ok(p.every(Number.isFinite),'Projection must remain finite through poles and inverted views');
    assert.ok(p[0]>=0&&p[0]<=390&&p[1]>=0&&p[1]<=460,'Default panorama must fit at every viewing angle');
  }
}
const above=createPerspectiveProjection(box,{...defaultCamera(),pitch:90},1400,700);
const below=createPerspectiveProjection(box,{...defaultCamera(),pitch:270},1400,700);
assert.ok(above.facing([0,0,0],[0,1,0]));assert.equal(above.facing([0,0,0],[0,-1,0]),false);
assert.ok(below.facing([0,0,0],[0,-1,0]));assert.equal(below.facing([0,0,0],[0,1,0]),false);
// Exercise the actual pointer handlers, including modifier gating and menu suppression.
const frames=new Map(), handlers=new Map();let frameId=0,drawn=[],resizeCallback;
globalThis.requestAnimationFrame=callback=>{frames.set(++frameId,callback);return frameId;};
globalThis.cancelAnimationFrame=id=>frames.delete(id);
globalThis.document={documentElement:{dataset:{theme:'dark'}}};
globalThis.window={devicePixelRatio:1};
globalThis.getComputedStyle=()=>({getPropertyValue:()=>''});
globalThis.ResizeObserver=class {constructor(callback){resizeCallback=callback;}observe(){resizeCallback();}disconnect(){}};
globalThis.MutationObserver=class {observe(){}disconnect(){}};
const context=new Proxy({measureText:text=>({width:text.length*7})},{get(target,key){return target[key] || ((...args)=>{if(['moveTo','lineTo'].includes(key))drawn.push([key,...args]);});}});
const fakeCanvas={getContext:()=>context,getBoundingClientRect:()=>({width:1400,height:700,left:0,top:0}),setPointerCapture(){},hasPointerCapture:()=>false,releasePointerCapture(){},addEventListener:(event,handler)=>handlers.set(event,handler),removeEventListener:event=>handlers.delete(event)};
let clicked=null;
const scene=createMatrixScene(fakeCanvas,value=>{clicked=value;});
const sample={tasks,date:'2026-10-01',server_time:'2026-10-01 13:30:00',records:[{pid:'0-000',key:'sample',time:'2026-10-01 12:00:00',status:'success'}],active:[],pending:[]};
const flush=()=>{drawn=[];for(const [id,fn] of [...frames]){frames.delete(id);fn();}return JSON.stringify(drawn);};
scene.update(sample,'',false,'');const original=flush();
const event=(overrides={})=>({pointerId:1,button:0,clientX:400,clientY:300,altKey:false,preventDefault(){},...overrides});
handlers.get('pointerdown')(event());handlers.get('pointermove')(event({clientX:600}));handlers.get('pointerup')(event({clientX:600}));
scene.update(sample,'',false,'');assert.equal(flush(),original,'Ordinary drag must not move camera');
handlers.get('pointerdown')(event({altKey:true}));handlers.get('pointermove')(event({clientX:450,altKey:true}));handlers.get('pointerup')(event({clientX:450}));
assert.notEqual(flush(),original,'Alt drag must change the rendered projection');
scene.restore();assert.equal(flush(),original,'Restore must retain the same data and reset only the camera');
handlers.get('pointerdown')(event({altKey:true}));handlers.get('pointermove')(event({clientY:3180,altKey:true}));handlers.get('pointerup')(event({clientY:3180}));
assert.equal(flush(),original,'Two vertical turns must return to the same scene without pole locking');
handlers.get('pointerdown')(event({altKey:true}));handlers.get('pointermove')(event({clientY:-180,altKey:true}));handlers.get('pointerup')(event({clientY:-180}));flush();
const sceneBounds={min:[-1.3,-.1,0],max:[layout.width,7.5,layout.depth+1]};
const inverted=createPerspectiveProjection(sceneBounds,{...defaultCamera(),pitch:-96},1400,700);
const taskPosition=layout.positions.get('0-000'),recordY=720*7.1/810+.045;
const point=inverted.project(taskPosition.x,recordY-.065,taskPosition.z);
handlers.get('pointerdown')(event({clientX:point[0],clientY:point[1]}));handlers.get('pointerup')(event({clientX:point[0],clientY:point[1]}));
assert.equal(clicked?.key,'sample','Execution records must still be clickable from their underside');
let blocked=false;
handlers.get('pointerdown')(event({altKey:true,button:2}));handlers.get('pointerup')(event({button:2}));handlers.get('contextmenu')(event({preventDefault(){blocked=true;}}));
assert.ok(blocked,'Right drag must suppress context menu even after Alt is released');
handlers.get('pointerdown')(event({button:2}));blocked=false;handlers.get('contextmenu')(event({preventDefault(){blocked=true;}}));assert.equal(blocked,false);
scene.dispose();assert.equal(handlers.size,0,'Unmount must release all pointer handlers');
console.log('Perspective depth, full rotations, inverted picking, camera, layout, context menu and cleanup passed.');
