[production]
dialect = 'mysql'
driver = 'pymysql'
user = 'IMMP'
password = '3c94cbeb53a08e6fc7b980157dd72794'
host = 'IMMP-DBS-01.ICBC'
port = '3306'
database = 'immpdb'


[development]
dialect = 'mysql'
driver = 'pymysql'
user = 'yyzc'
password = 'f46b89c2e3d26d09'
# host = '76.13.77.234'
host = '76.13.45.4'
port = '3306'
database = 'immpdb'
