#所有业务数据的配置文件
[oracle_rmf]
dialect = 'oracle'
user = 'rmf'
password = 'ef40e7916a35c5b17df3fb9b71a993c4'
host = '76.125.40.108'
port = '1521'
database = 'IMMPDB1'

[oracle_tb0a]
dialect = 'oracle'
user = 'tb0a'
password = 'eadeb0c693402ed17df3fb9b71a993c4'
host = '76.7.50.190'
port = '1521'
database = 'IMMPDB2'

[oracle_bsm]
dialect = 'oracle'
user = 'tb0a'
password = 'eadeb0c693402ed17df3fb9b71a993c4'
host = '76.125.40.108'
port = '1521'
database = 'BSM'

[mysql_immpdb]
dialect = 'mysql'
user = 'IMMP'
password = '3c94cbeb53a08e6fc7b980157dd72794'
host = 'IMMP-DBS-01.ICBC'
port = '3306'
database = 'immpdb'

[mysql_immp_dbs_01]
dialect = 'mysql'
user = 'IMMP'
password = '3c94cbeb53a08e6fc7b980157dd72794'
host = 'IMMP-DBS-01.ICBC'
port = '3306'

[mysql_mfri]
dialect = 'mysql'
user = 'IMMP'
password = '3c94cbeb53a08e6fc7b980157dd72794'
host = 'IMMP-DBS-01.ICBC'
port = '3306'
database = 'mfri'

[mysql_job_immp]
dialect = 'mysql'
user = 'IMMP'
password = '3c94cbeb53a08e6fc7b980157dd72794'
host = '84.49.22.48'
port = '3306'
database = 'job_immp'

[mysql_xnrl]
dialect = 'mysql'
user = 'xnrl'
password = '43c9e981bf351ef27a4359c3712e55e2'
host = 'lab-tidb.icbc'
port = '4000'
database = 'xnrldb'

[mysql_mo_gsyh]
dialect = 'mysql'
user = 'root'
password = '2950f68d633c3862636248adb2f1aa2e'
host = '76.124.202.211'
port = '3306'
database = 'mo_gsyh'

[mysql_drp_184]
dialect = 'mysql'
user = 'drpnw'
password = '960bfd0db9fc7cfe7df3fb9b71a993c4'
host = '84.137.246.184'
port = '3306'
database = 'binlogplus'

[mysql_drp_162]
dialect = 'mysql'
user = 'drpnw'
password = '960bfd0db9fc7cfe7df3fb9b71a993c4'
host = '84.130.27.162'
port = '3306'
database = 'binlogplus_golden'

[mysql_drp_web]
dialect = 'mysql'
user = 'drpnw'
password = '960bfd0db9fc7cfe7df3fb9b71a993c4'
host = '84.170.30.143'
port = '3306'
database = 'drpweb'

[mysql_dmqs_wgq_dble_01]
dialect = 'mysql'
user = 'dmqs'
password = '56637e6a06d3ff637df3fb9b71a993c4'
host = 'DMQS-DBS-DOMESTIC-DBLE-01.ICBC'
port = '8066'
database = 'dmqsdb'

[mysql_dmqs_set9]
dialect = 'mysql'
user = 'dmqs'
password = '56637e6a06d3ff637df3fb9b71a993c4'
host = 'DMQS-DBS-DOMESTIC-DBLE-01.ICBC'
port = '8066'
database = 'dmqsdb'

[sybase_ncoms]
dialect = 'sybase'
user = 'xtyb'
password = '7917449e0be74631'
host = '84.7.163.101'
port = '4100'
database = 'NCOMS'

[redis]
host='84.125.2.8'
port='6379'
password='1709326a5ba3f77b7df3fb9b71a993c4'
max_connections='50'
database='1'

[redis_lab_cluster]
startup_nodes='[{"host": "76.71.34.1", "port": "6379"},{"host": "76.71.34.2", "port": "6379"},{"host": "76.71.34.3", "port": "6379"},{"host": "76.71.34.1", "port": "6479"},{"host": "76.71.34.2", "port": "6479"},{"host": "76.71.34.3", "port": "6479"}]'
password='a086d99c382f2389'
max_connections='50'

[redis_single_node]
host='76.71.34.2'
port='6579'
password='a086d99c382f2389'
max_connections='50'
database='0'

[clickhouse_default_55]
dialect = 'clickhouse'
user='default'
password='d4a0d164b4f301417df3fb9b71a993c4'
host='76.125.40.55'
port='8123'
database='default'

[clickhouse_default_58]
dialect = 'clickhouse'
user='default'
password='d4a0d164b4f301417df3fb9b71a993c4'
host='76.125.40.58'
port='8123'
database='default'

